vim.cmd[[set termguicolors]]
vim.cmd[[set guicursor=n-v-c-sm:blinkon100,i-ci-ve:ver25blinkon100,r-cr-o:hor20blinkon100]]
vim.cmd[[hi Cursor gui=reverse guibg=reverse guifg=reverse]]
vim.cmd[[hi CursorLine gui=reverse guibg=reverse guifg=reverse]]
vim.cmd[[hi TermCursor gui=reverse guibg=reverse guifg=reverse cterm=reverse]]
vim.cmd[[hi TermCursorNC gui=reverse guibg=reverse guifg=reverse cterm=reverse]]
vim.cmd[[colorscheme dracula]]
