vim.g.mapleader = " "
vim.g.localmapleader = " "

vim.keymap.set("n", "<Space>", "", {})
vim.keymap.set("n", "<F1>", "", {})
vim.keymap.set("n", "Q", "")
vim.keymap.set("n", "<ESC>", "<CMD>noh<CR>", { silent = true })
vim.keymap.set("n", "<A-,>", "<CMD>BufferLineCyclePrev<CR>", { silent = true })
vim.keymap.set("n", "<A-.>", "<CMD>BufferLineCycleNext<CR>", { silent = true })
vim.keymap.set("n", "<A-t>", "<CMD>BufferLineCloseOthers<CR>", { silent = true })
vim.keymap.set("n", "<A-c>", "<CMD>BufDel<CR>", { silent = true })
vim.keymap.set("n", ",", "<CMD>BufferLineCyclePrev<CR>", { silent = true })
vim.keymap.set("n", ".", "<CMD>BufferLineCycleNext<CR>", { silent = true })
vim.keymap.set("n", "L", "<CMD>BufferLineCycleNext<CR>", { silent = true })
vim.keymap.set("n", "H", "<CMD>BufferLineCyclePrev<CR>", { silent = true })
vim.keymap.set("n", "<C-n>", "<CMD>BufferLineMoveNext<CR>", { silent = true })
vim.keymap.set("n", "<C-m>", "<CMD>BufferLineMovePrev<CR>", { silent = true })
vim.keymap.set("n", "<C-t>", "<CMD>BufferLineCloseOthers<CR>", { silent = true })
vim.keymap.set("n", "<C-c>", "<CMD>BufDel<CR>", { silent = true })
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv", { silent = true })
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv", { silent = true })
vim.keymap.set("n", "n", "nzzzv", { silent = true })
vim.keymap.set("n", "N", "Nzzzv", { silent = true })
vim.keymap.set("n", "<F8>", "<CMD>lua require('dap').continue()<CR>")
vim.keymap.set("n", "<F9>", "<CMD>lua require('dap').step_into()<CR>")
vim.keymap.set("n", "<F10>", "<CMD>lua require('dap').step_over()<CR>")
vim.keymap.set("n", "<F11>", "<CMD>lua require('dap').step_out()<CR>")

vim.keymap.set("n", "<leader>,", "<CMD>BufferLineCyclePrev<CR>", { desc = "Cycle to next buffer" })
vim.keymap.set("n", "<leader>.", "<CMD>BufferLineCycleNext<CR>", { desc = "Cycle to previous buffer" })
vim.keymap.set("n", "<leader>L", "<CMD>Lazy<CR>", { desc = "Lazy" })
vim.keymap.set("n", "<leader>M", "<CMD>Mason<CR>", { desc = "Mason" })
vim.keymap.set("n", "<leader>b", "<CMD>Telescope buffers<CR>", { desc = "Opened buffers" })
vim.keymap.set("n", "<leader>c", "<CMD>BufDel<CR>", { desc = "Close current buffer" })
vim.keymap.set("n", "<leader>e", "<CMD>Neotree toggle<CR>", { desc = "File Explorer" })
vim.keymap.set("n", "<leader>f", "<CMD>Telescope live_grep_args<CR>", { desc = "Search in files" })

vim.keymap.set("n", "<leader>ha", "<CMD>lua require('harpoon.mark').add_file()<CR>", { desc = "Add mark" })
vim.keymap.set("n", "<leader>he", "<CMD>lua require('harpoon.ui').toggle_quick_menu()<CR>", { desc = "Show menu" })
vim.keymap.set("n", "<leader>hm", "<CMD>Telescope harpoon marks<CR>", { desc = "Show marks" })
vim.keymap.set("n", "<leader>nd", "<CMD>Noice dismiss<CR>", { desc = "Dismiss notifications" })
vim.keymap.set("n", "<leader>o", "<CMD>Neotree reveal<CR>", { desc = "Open file in explorer" })
vim.keymap.set("n", "<leader>p", "<CMD>lua require('telescope.builtin').find_files({find_command = { 'fd', '-t=f', '-H' }})<CR>", { desc = "Search files" })
vim.keymap.set("n", "<leader>r", "<CMD>Telescope frecency workspace=CWD<CR>", { desc = "Recent files" })
vim.keymap.set("n", "<leader>s", "<CMD>lua require('treesj').toggle()<CR>", { desc = "Join the object under cursor" })
vim.keymap.set("n", "<leader>t", "<CMD>BufferLineCloseOthers<CR>", { desc = "Close other buffers" })

vim.keymap.set("n", "<leader>ghP", "<CMD>Gitsigns preview_hunk<CR>", { desc = "Preview hunk" })
vim.keymap.set("n", "<leader>ghn", "<CMD>Gitsigns next_hunk<CR>", { desc = "Next hunk" })
vim.keymap.set("n", "<leader>ghp", "<CMD>Gitsigns prev_hunk<CR>", { desc = "Previous hunk" })
vim.keymap.set("n", "<leader>ghr", "<CMD>Gitsigns reset_hunk<CR>", { desc = "Reset hunk" })
vim.keymap.set("n", "<leader>ghs", "<CMD>Gitsigns select_hunk<CR>", { desc = "Select hunk" })

vim.keymap.set("n", "<leader>gwc", "<CMD>lua require('telescope').extensions.git_worktree.create_git_worktree()<CR>", { desc = "Create worktree" })
vim.keymap.set("n", "<leader>gws", "<CMD>lua require('telescope').extensions.git_worktree.git_worktrees()<CR>", { desc = "Switch worktrees" })

vim.keymap.set({ "n", "o", "x" }, "w", "<CMD>lua require('spider').motion('w')<CR>", { desc = "Spider-w" })
vim.keymap.set({ "n", "o", "x" }, "e", "<CMD>lua require('spider').motion('e')<CR>", { desc = "Spider-e" })
vim.keymap.set({ "n", "o", "x" }, "b", "<CMD>lua require('spider').motion('b')<CR>", { desc = "Spider-b" })
vim.keymap.set({ "n", "o", "x" }, "ge", "<CMD>lua require('spider').motion('ge')<CR>", { desc = "Spider-ge" })
vim.keymap.set("n", "]g", "<CMD>Gitsigns next_hunk<CR>", { desc = "Git next hunk" })
vim.keymap.set("n", "[g", "<CMD>Gitsigns prev_hunk<CR>", { desc = "Git prev hunk" })

local status, live_grep_args_shortcuts = pcall(require, "telescope-live-grep-args.shortcuts")
if status then
    vim.keymap.set("v", "<C-f>", live_grep_args_shortcuts.grep_visual_selection, { desc = "Search visual selection" })
    vim.keymap.set("n", "<C-f>", live_grep_args_shortcuts.grep_word_under_cursor, { desc = "Search word under cursor" })
end
